import { useState, useEffect } from "react";
import { useNavigate, Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { supabase } from "@/integrations/supabase/client";
import { Play, ArrowRight, CheckCircle2, Brain, Target, Sparkles, Loader2 } from "lucide-react";
import { Logo } from "@/components/ui/Logo";
import { GradientButton } from "@/components/ui/GradientButton";
import { AnimatedCard } from "@/components/ui/AnimatedCard";

const Index = () => {
  const navigate = useNavigate();
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    supabase.auth.getSession().then(({ data: { session } }) => {
      if (session?.user) {
        navigate("/dashboard");
      }
      setLoading(false);
    });
  }, [navigate]);

  if (loading) {
    return (
      <div className="min-h-screen gradient-page flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  const features = [
    {
      icon: Brain,
      title: "AI-Powered Questions",
      description: "Get intelligent, role-specific interview questions generated by advanced AI models.",
    },
    {
      icon: Target,
      title: "Instant Feedback",
      description: "Receive detailed feedback on your answers with scores, strengths, and areas to improve.",
    },
    {
      icon: Sparkles,
      title: "Track Progress",
      description: "Monitor your improvement over time with detailed analytics and performance insights.",
    },
  ];

  return (
    <div className="min-h-screen gradient-page overflow-hidden">
      {/* Background decorations */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        <div className="absolute -top-40 -right-40 w-96 h-96 rounded-full bg-primary/10 blur-3xl animate-float" />
        <div className="absolute top-1/2 -left-40 w-80 h-80 rounded-full bg-accent/10 blur-3xl" style={{ animationDelay: "1s" }} />
        <div className="absolute -bottom-20 right-1/4 w-64 h-64 rounded-full bg-primary/5 blur-3xl" />
      </div>

      {/* Header */}
      <header className="relative z-10 border-b border-border/50 glass">
        <div className="container mx-auto px-4 py-4 flex items-center justify-between">
          <Logo size="md" />
          <Link to="/auth">
            <Button variant="ghost" className="text-muted-foreground hover:text-foreground">
              Sign In
              <ArrowRight className="w-4 h-4 ml-2" />
            </Button>
          </Link>
        </div>
      </header>

      {/* Hero Section */}
      <main className="relative z-10">
        <section className="container mx-auto px-4 py-20 md:py-32">
          <div className="max-w-3xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-sm font-medium mb-8 animate-fade-in-up">
              <Sparkles className="w-4 h-4" />
              AI-Powered Interview Practice
            </div>
            
            <h1 className="text-4xl md:text-6xl font-bold text-foreground mb-6 leading-tight animate-fade-in-up" style={{ animationDelay: "100ms" }}>
              Master Your Interviews with{" "}
              <span className="gradient-text">MockMate AI</span>
            </h1>
            
            <p className="text-lg md:text-xl text-muted-foreground mb-10 max-w-2xl mx-auto animate-fade-in-up" style={{ animationDelay: "200ms" }}>
              Practice with AI-generated interview questions, get instant feedback, 
              and track your progress to land your dream job.
            </p>
            
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 animate-fade-in-up" style={{ animationDelay: "300ms" }}>
              <Link to="/auth">
                <GradientButton size="lg" icon={<Play className="w-5 h-5" />}>
                  Start Practicing Free
                </GradientButton>
              </Link>
              <Link to="/auth">
                <Button variant="outline" size="lg" className="h-14 px-8 text-lg">
                  Learn More
                </Button>
              </Link>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section className="container mx-auto px-4 py-16">
          <div className="grid md:grid-cols-3 gap-6 max-w-5xl mx-auto">
            {features.map((feature, index) => (
              <AnimatedCard
                key={feature.title}
                variant="glass"
                hover="lift"
                delay={index * 100 + 400}
                className="p-6"
              >
                <div className="p-3 rounded-xl gradient-brand w-fit mb-4 shadow-brand">
                  <feature.icon className="w-6 h-6 text-primary-foreground" />
                </div>
                <h3 className="text-lg font-semibold text-foreground mb-2">{feature.title}</h3>
                <p className="text-muted-foreground text-sm">{feature.description}</p>
              </AnimatedCard>
            ))}
          </div>
        </section>

        {/* How It Works Section */}
        <section className="container mx-auto px-4 py-16">
          <div className="max-w-3xl mx-auto">
            <h2 className="text-2xl md:text-3xl font-bold text-center text-foreground mb-12">
              How It <span className="gradient-text">Works</span>
            </h2>
            
            <div className="space-y-6">
              {[
                { step: "1", title: "Choose Your Role", desc: "Select your target job role and difficulty level" },
                { step: "2", title: "Answer Questions", desc: "Practice with AI-generated MCQ or descriptive questions" },
                { step: "3", title: "Get Feedback", desc: "Receive instant AI feedback with scores and improvement tips" },
              ].map((item, index) => (
                <div 
                  key={item.step}
                  className="flex items-start gap-4 p-4 rounded-xl bg-card border border-border hover:shadow-md transition-all animate-fade-in-up"
                  style={{ animationDelay: `${index * 100 + 700}ms` }}
                >
                  <div className="w-10 h-10 rounded-full gradient-brand flex items-center justify-center text-primary-foreground font-bold flex-shrink-0">
                    {item.step}
                  </div>
                  <div>
                    <h3 className="font-semibold text-foreground">{item.title}</h3>
                    <p className="text-muted-foreground text-sm">{item.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section className="container mx-auto px-4 py-20">
          <AnimatedCard 
            variant="gradient" 
            hover="none" 
            delay={1000}
            className="max-w-2xl mx-auto text-center p-10"
          >
            <h2 className="text-2xl md:text-3xl font-bold text-foreground mb-4">
              Ready to ace your next interview?
            </h2>
            <p className="text-muted-foreground mb-8">
              Join thousands of candidates who improved their interview skills with MockMate AI.
            </p>
            <Link to="/auth">
              <GradientButton size="lg" icon={<ArrowRight className="w-5 h-5" />}>
                Get Started Now
              </GradientButton>
            </Link>
          </AnimatedCard>
        </section>
      </main>

      {/* Footer */}
      <footer className="relative z-10 border-t border-border/50 py-8">
        <div className="container mx-auto px-4 text-center">
          <Logo size="sm" className="justify-center mb-4" />
          <p className="text-sm text-muted-foreground">
            © 2024 MockMate AI. Free AI-powered interview practice for students and professionals.
          </p>
        </div>
      </footer>
    </div>
  );
};

export default Index;
